parent_product_name: DTHadoop
product_name: Mysql
product_version: 5.7.38
service:

  mysql:
    version: 5.7.38
    instance:
      cmd: ./bin/mysql.sh ${is_other}
      config_paths:
        - my.cnf
      max_replica: 1
      healthcheck:
        shell: ./health.sh ${@mysql} ${user} ${password} ${is_other}
        period: 20s
        retries: 2
      logs:
        - /data/my3306/log/alert.log
      post_deploy: ./post_deploy.sh ${user} ${password} ${repl_user} ${repl_password} ${check_num} ${is_other}
      update_recreate: true
      prometheus_port: 9104
      ha_role_cmd: ./show_mysql_state.sh ${@mysql} ${user} ${password} 2>/dev/null
    group: mysql
    config:
      user: drpeco
      password: DT@Stack#123
      encryption_mysql_password: XdVyOxV50S7MA8qMfYJJFwzHpmz0qTeiObElsfOYVcQsqjUGZEZyRW+lI76vZ/BIuHb66ac3YmAvFWJD8NOPkcWcJGdMJJK+XgVs9iIVe8NP+7hmXLR7Ah5mgI5lYqbIKQ8D82TiA5D5WuU203wUqdUARGt8s8gwLXGimoIOJjg=
      repl_user: repl
      repl_password: drpEco@123
      port: 3306
      db: metastore
      tengine_ip: 127.0.0.1
      check_num: 3
      data1_len: "10G"
      data2_len: "500M"
      interactive_timeout: 12000
      wait_timeout: 12000
      max_connections: 5000
      pid_file: "/data/my3306/run/mysqld.pid"
      basedir: "/opt/dtstack/Mysql/mysql"
      datadir: "/data/my3306/data"
      tmpdir: "/data/my3306/tmp"
      socket: "/data/my3306/run/mysql.sock"
      log_error: "/data/my3306/log/alert.log"
      log_error_verbosity: 1
      slow_query_log: 1
      long_query_time: 0.5
      log_slow_admin_statements: 1
      slow_query_log_file: "/data/my3306/log/slow.log"
      general_log: 0
      general_log_file: "/data/my3306/log/general.log"
      skip_symbolic_links: "yes"
      local_infile: 0
      character_set_server: "utf8"
      lower_case_table_names: 1
      skip_external_locking: 1
      open_files_limit: 65535
      safe_user_create: 1
      performance_schema: 0
      auto_increment_increment: 2
      auto_increment_offset: 1
      innodb_buffer_pool_size: 2G
      innodb_flush_method: "O_DIRECT"
      innodb_file_per_table: 1
      innodb_log_files_in_group: 3
      innodb_log_file_size: "256M"
      innodb_buffer_pool_instances: 4
      innodb_log_buffer_size: "32M"
      innodb_flush_log_at_trx_commit: 1
      innodb_open_files: 1024
      innodb_data_home_dir: "/data/my3306/data"
      innodb_log_group_home_dir: "/data/my3306/data"
      log_bin: "/data/my3306/log/mysql_bin"
      binlog_cache_size: "32K"
      max_binlog_cache_size: "2G"
      max_binlog_size: "512M"
      binlog_format: "ROW"
      sync_binlog: 1
      log_slave_updates: 1
      expire_logs_days: 10
      innodb_io_capacity: 200
      innodb_max_dirty_pages_pct: 75
      innodb_thread_concurrency: 16
      innodb_read_io_threads: 8
      innodb_write_io_threads: 8
      innodb_file_format: "Barracuda"
      innodb_change_buffering: "all"
      innodb_adaptive_flushing: 1
      innodb_old_blocks_time: 1000
      innodb_stats_on_metadata: 0
      innodb_use_native_aio: 0
      innodb_lock_wait_timeout: 50
      innodb_rollback_on_timeout: 0
      innodb_purge_threads: 1
      innodb_strict_mode: 1
      transaction_isolation: "READ-COMMITTED"
      innodb_autoinc_lock_mode: 1
      sql_mode: "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
      relay_log: "/data/my3306/log/mysqld-relay-bin"
      relay_log_index: "/data/my3306/log/mysqld-relay-bin.index"
      master_info_file: "/data/my3306/log/master.info"
      relay_log_info_file: "/data/my3306/log/relay-log.info"
      server_id: 208
      key_buffer_size: "50M"
      myisam_sort_buffer_size: "50M"
      concurrent_insert: 2
      delayed_insert_timeout: 300
      read_rnd_buffer_size: "2M"
      sort_buffer_size: "2M"
      join_buffer_size: "2M"
      read_buffer_size: "2M"
      table_open_cache: 400
      thread_cache_size: 256
      max_user_connections: 0
      max_connect_errors: 100000
      max_allowed_packet: "128M"
      query_cache_type: 2
      query_cache_limit: "1M"
      query_cache_min_res_unit: "1K"
      query_cache_size: "200M"
      skip_name_resolve: 1
      sysdate_is_now: 1
      connect_timeout: 10
      net_read_timeout: 30
      net_write_timeout: 60
      back_log: 512
      old_passwords: 0
      is_other: "false"
      log_bin_trust_function_creators: "ON"


    mysql_slave:
      version: 5.7.38
      instance:
        cmd: ./bin/mysql.sh
        config_paths:
          - my.cnf
        max_replica: 1
        healthcheck:
          shell: ./health.sh ${@mysql_slave} ${mysql_user} ${mysql_password}
          period: 20s
          retries: 2
        logs:
          - /data/my3306/log/alert.log
        post_deploy: ./post_deploy.sh ${@mysql} ${mysql.repl_user} ${mysql.repl_password} ${mysql.user} ${mysql.password} ${check_num}
        update_recreate: true
        prometheus_port: 9104
        ha_role_cmd: ./show_mysql_state.sh ${@mysql_slave} ${mysql_user} ${mysql_password} 2>/dev/null
      group: mysql
      depends_on:
        - mysql
      config:
        mysql_host: ${@mysql}
        mysql_user: ${mysql.user}
        mysql_password: ${mysql.password}
        data1_len: "10G"
        data2_len: "500M"
        pid_file: "/data/my3306/run/mysqld.pid"
        port: 3306
        default_character_set: "utf8"
        check_num: ${mysql.check_num}
        basedir: "/opt/dtstack/Mysql/mysql_slave"
        datadir: "/data/my3306/data"
        tmpdir: "/data/my3306/tmp"
        socket: "/data/my3306/run/mysql.sock"
        log_error: "/data/my3306/log/alert.log"
        log_error_verbosity: 1
        slow_query_log: 1
        long_query_time: 0.5
        log_slow_admin_statements: 1
        slow_query_log_file: "/data/my3306/log/slow.log"
        general_log: 0
        general_log_file: "/data/my3306/log/general.log"
        skip_symbolic_links: "yes"
        local_infile: 0
        character_set_server: "utf8"
        lower_case_table_names: 1
        skip_external_locking: 1
        open_files_limit: 65535
        safe_user_create: 1
        performance_schema: 0
        max_connect_errors: 100000
        auto_increment_increment: 2
        auto_increment_offset: 1
        read_only: 1
        innodb_buffer_pool_size: "2G"
        innodb_flush_method: "O_DIRECT"
        innodb_file_per_table: 1
        innodb_log_files_in_group: 3
        innodb_log_file_size: "256M"
        innodb_buffer_pool_instances: 4
        innodb_log_buffer_size: "32M"
        innodb_flush_log_at_trx_commit: 1
        innodb_open_files: 1024
        innodb_data_home_dir: "/data/my3306/data"
        innodb_log_group_home_dir: "/data/my3306/data"
        log_bin: "/data/my3306/log/mysql_bin"
        binlog_cache_size: "32K"
        max_binlog_cache_size: "1G"
        max_binlog_size: "512M"
        binlog_format: "ROW"
        sync_binlog: 1
        log_slave_updates: 1
        expire_logs_days: 10
        innodb_io_capacity: 200
        innodb_max_dirty_pages_pct: 75
        innodb_thread_concurrency: 16
        innodb_read_io_threads: 8
        innodb_write_io_threads: 8
        innodb_file_format: "Barracuda"
        innodb_change_buffering: "all"
        innodb_adaptive_flushing: 1
        innodb_old_blocks_time: 1000
        innodb_stats_on_metadata: 0
        innodb_use_native_aio: 0
        innodb_lock_wait_timeout: 50
        innodb_rollback_on_timeout: 0
        innodb_purge_threads: 1
        innodb_strict_mode: 1
        transaction_isolation: "READ-COMMITTED"
        innodb_autoinc_lock_mode: 1
        sql_mode: "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
        relay_log: "/data/my3306/log/mysqld-relay-bin"
        relay_log_index: "/data/my3306/log/mysqld-relay-bin.index"
        master_info_file: "/data/my3306/log/master.info"
        relay_log_info_file: "/data/my3306/log/relay-log.info"
        server_id: 308
        key_buffer_size: "50M"
        myisam_sort_buffer_size: "50M"
        concurrent_insert: 2
        delayed_insert_timeout: 300
        read_rnd_buffer_size: "128K"
        sort_buffer_size: "2M"
        join_buffer_size: "2M"
        read_buffer_size: "2M"
        table_open_cache: 400
        thread_cache_size: 256
        max_connections: 5000
        max_user_connections: 2000
        max_allowed_packet: "128M"
        query_cache_type: 2
        query_cache_limit: "1M"
        query_cache_min_res_unit: "1K"
        query_cache_size: "200M"
        skip_name_resolve: 1
        sysdate_is_now: 1
        connect_timeout: 10
        net_read_timeout: 30
        net_write_timeout: 60
        back_log: 512
        old_passwords: 0
        log_bin_trust_function_creators: "ON"
